server:
  port: 3000
  context-path: /uaa

api_service_url: "http://api:8080"

spring:
  redis:
    host: redis
    port: 6379
    password: password
  auth:
    client:
      id: "hendi-client"
      secret: "{noop}hendi-secret"

hystrix:
  command:
    default:
      fallback.enabled: false

logging:
  config: classpath:log4j2.xml