message: test
config:
  rpc:
    minEcTenderCommitteeNode:
      host: localhost
      password: c0rd@pass
      port: 10004
      username: apiUser
    fasNode:
      host: localhost
      password: c0rd@pass
      port: 10006
      username: apiUser
    kaznaNode:
      host: localhost
      password: c0rd@pass
      port: 10008
      username: apiUser

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  ldap:
    embedded:
      ldif: 'classpath:test-server.ldif'
      base-dn: 'dc=springframework,dc=org'
      port: 8389
  jackson:
    default-property-inclusion: non_null
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    database: default
    show-sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5433/postgres
    user: postgres
    password: postgres
  data:
    web:
      pageable:
        default-page-size: 10

minec:
  datasource:
    jdbcUrl: jdbc:h2:tcp://127.0.0.1:11000/node
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  config: classpath:log4j2.yml
#  level:
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE

ad:
  domain: "local"
  url: "ldap://localhost:8389/"
  dc: "dc=springframework,dc=org"

server:
  port: 8080

jasperreports:
  generation:
    folder: /tmp

dadata-webservice:
  token: "Token a3457efc8c2e212e7d6a78a32b8bfd194e8d1572"
  url: "https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/party"

zakupki-gov-ru-ftp:
  host: ftp.zakupki.gov.ru
  username: free
  password: free
  folder:
    1: /fcs_regions/Moskva/notifications/currMonth/
    2: /fcs_regions/Moskva/notifications/prevMonth/
    3: /fcs_regions/Moskva/notifications/
