config:
  rpc:
    minEcTenderCommitteeNode:
      host: "minec"
      password: "c0rd@pass"
      port: 10004
      username: "apiUser"
    fasNode:
      host: "fas"
      password: "c0rd@pass"
      port: 10006
      username: "apiUser"
    kaznaNode:
      host: "kazna"
      password: "c0rd@pass"
      port: 10008
      username: "apiUser"

spring:
  ldap:
    embedded:
      ldif: "classpath:test-server.ldif"
      base-dn: "dc=springframework,dc=org"
      port: 8389
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://minec-api-db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database: default
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://minec-api-db:5432/postgres
    user: postgres
    password: postgres
    #location: ["classpath:db/migration", "classpath:db/prod"]
  data:
    web:
      pageable:
        default-page-size: 10
  auth:
    client:
      id: "hendi-client"
      secret: "hendi-secret"
      checkTokenUrl: "http://auth-service:5000/oauth/check_token"

minec:
  datasource:
    jdbcUrl: jdbc:h2:tcp://minec:11000/node
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    config: classpath:log4j2.yml
    org.springframework.security: DEBUG

ad:
  domain: "local"
  url: "ldap://localhost:8389/"
  dc: "dc=springframework,dc=org"

management:
    security:
           enabled: false

jasperreports:
  generation:
    folder: /tmp

management.security.enabled: false

dadata-webservice:
  token: "Token a3457efc8c2e212e7d6a78a32b8bfd194e8d1572"
  url: "https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/party"

zakupki-gov-ru-ftp:
  host: ftp.zakupki.gov.ru
  username: free
  password: free
  folder:
    1: /fcs_regions/Moskva/notifications/currMonth/
    2: /fcs_regions/Moskva/notifications/prevMonth/
    3: /fcs_regions/Moskva/notifications/
